version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    # volumes:
    #   - ./opt/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
